services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=runnerz'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=quilla'
    ports:
      - '5432:5432' #Maps port 5432 on Docker to local 5432 port